"""Render a ScanResult as a Markdown report.

Output lands in ~/.painscope/reports/<scan_id>.md by default.
Reports are designed to be readable in Obsidian, Notion, or plain GitHub markdown.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from jinja2 import Template

from painscope.config import get_settings
from painscope.pipeline.orchestrator import ScanResult

REPORT_TEMPLATE = Template(
    """# {{ result.source | capitalize }}{% if result.source == "multi" %} ({{ result.target }}){% else %} — {{ result.target }}{% endif %}

**Scan ID:** `{{ result.scan_id }}`
**Type:** {{ result.scan_type }}
**Language:** {{ result.language }}
**Model:** {{ result.model_used or "default" }}
**Started:** {{ result.started_at.strftime("%Y-%m-%d %H:%M UTC") }}
**Duration:** {{ "%.1f"|format(result.duration_seconds) }}s
**Posts:** {{ result.total_posts_used }} / {{ result.total_posts_fetched }} fetched
**Clusters:** {{ result.num_clusters }}

{% if result.sources %}
## Sources Scanned
{% for s in result.sources %}
- **{{ s.label }}** — {{ s.posts_fetched }} posts{% if s.get("error") %} ⚠️ error: {{ s.error }}{% endif %}

{% endfor %}
{% endif %}
---

{% if not result.insights %}
_No insights extracted — not enough signal in the fetched posts._
{% else %}
{% for insight in result.insights %}
## {{ loop.index }}. {{ insight.title }}

{% if insight.severity is defined %}
**Severity:** {{ insight.severity }}/5 · **Cluster size:** {{ insight._cluster_size }} · **Score:** {{ insight._score }}

{{ insight.summary }}

**Content angle:** {{ insight.content_angle }}
{% else %}
**Cluster size:** {{ insight._cluster_size }} · **Score:** {{ insight._score }}

**Angle:** {{ insight.angle }}

**Questions it answers:**
{% for q in insight.target_questions %}
- {{ q }}
{% endfor %}
{% endif %}

{% if insight.source_distribution %}
**Sources:** {% for label, count in insight.source_distribution.items() %}{{ label }} ({{ count }}){% if not loop.last %}, {% endif %}{% endfor %}

{% endif %}
**Quotes:**
{% for quote in insight.quotes %}
> {{ quote.text }}
> — [source]({{ quote.url }})
{% endfor %}

---
{% endfor %}
{% endif %}

_Generated by painscope_
"""
)


def render_markdown(result: ScanResult) -> str:
    return REPORT_TEMPLATE.render(result=result)


def save_report(result: ScanResult, out_dir: Path | None = None) -> Path:
    if out_dir is None:
        out_dir = get_settings().reports_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{result.scan_id}.md"
    path.write_text(render_markdown(result), encoding="utf-8")
    return path
